parameters:
#    sh_cloud_openstack.example.class: SHCloud\OpenstackBundle\Example

services:
#    sh_cloud_openstack.example:
#        class: %sh_cloud_openstack.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
